# Generated by Django 5.2 on 2025-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
