# Generated by Django 5.2 on 2025-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
