# Generated by Django 5.2 on 2025-04-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_website', '0003_alter_photo_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
